export type ApplicationErrorCode =
  | "unauthenticated"
  | "forbidden"
  | "player_not_found"
  | "group_not_found"
  | "membership_not_found"
  | "already_member"
  | "invalid_role_transition"
  | "ownership_invariant_violation"
  | "concurrency_conflict"
  | "match_not_found"
  | "match_not_open"
  | "already_joined"
  | "not_participating"
  | "roster_locked"
  | "invalid_match_transition"
  | "capacity_below_confirmed"
  | "invalid_capacity"
  | "group_archived"
  | "active_matches_prevent_archive"
  | "invalid_final_roster"
  | "roster_not_confirmed"
  | "stats_not_allowed"
  | "voting_not_found"
  | "voting_not_eligible_yet"
  | "voting_not_open"
  | "voter_not_eligible"
  | "invalid_ballot"
  | "ballot_already_submitted"
  | "progression_not_ready"
  | "invalid_progression_evidence"
  | "invalid_cursor"
  | "notification_not_found"
  | "invalid_connection"
  | "connection_not_found"
  | "connection_required"
  | "membership_required"
  | "progression_out_of_order"
  | "progression_config_not_found"
  | "invalid_team_assignment"
  | "teams_locked"
  | "incomplete_team_assignments"
  | "invalid_sporting_result"
  | "sporting_result_not_ready"
  | "sporting_result_locked"
  | "sporting_result_not_confirmed"
  | "prior_match_sporting_closure_required"
  | "invitation_not_available"
  | "invalid_invitation"
  | "member_blocked"
  | "guest_not_found"
  | "guest_name_conflict"
  | "guest_policy_disabled"
  | "guest_allowance_exceeded"
  | "guest_not_reusable"
  | "invalid_football_preferences"
  | "venue_candidate_conflict"
  | "court_candidate_conflict"
  | "venue_not_found"
  | "city_not_found"
  | "invalid_city_key"
  | "province_not_found"
  | "country_not_found"
  | "invalid_province_key"
  | "invalid_country_key"
  | "invalid_geography"
  | "court_requires_venue"
  | "court_not_at_venue"
  | "invalid_location"
  | "invalid_recruitment"
  | "media_not_found"
  | "media_feature_unavailable"
  | "media_storage_unavailable"
  | "media_rate_limited"
  | "invalid_media_upload"
  | "media_too_large"
  | "media_format_not_allowed"
  | "media_dimensions_invalid"
  | "media_processing_failed"
  | "invalid_queue_override"
  | "account_anonymized"
  | "account_deletion_requires_group_resolution"
  | "compliance_required"
  | "date_of_birth_required"
  | "date_of_birth_locked"
  | "invalid_date_of_birth"
  | "underage"
  | "report_rate_limited"
  | "invalid_report_target"
  | "report_target_not_found"
  | "admin_required"
  | "admin_target_not_found"
  | "account_suspended"
  | "already_suspended"
  | "not_suspended"
  | "invalid_moderation_state"
  | "progression_already_materialized"
  | "report_already_resolved"
  | "invitation_not_revocable";

export class ApplicationError extends Error {
  constructor(
    readonly code: ApplicationErrorCode,
    message: string,
    readonly statusCode: number,
    readonly details?: Record<string, unknown>,
  ) {
    super(message);
    this.name = "ApplicationError";
  }
}
